name: Ruby Errors

on:
  push:
    branches:
      - feat-errores
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - name: Install dependencies
      run: gem install test-unit

    - name: Run Ruby tests
      run: ruby ./temas/errores/ruby/testCalculator.rb

  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - name: Run Ruby script
      run: ruby ./temas/errores/ruby/calculator.rb
