name: Inyección Lua (Marta y Sergio)

on: 
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Lua
      uses: MunifTanjim/luver-action@v1

    - run: |
        luver install lua 5.4.3
        luver use 5.4.3
        luver install luarocks 3.8.0
        luarocks install luacheck
      

    - name: Run Lua script
      run: lua ./temas/inyeccion/lua/main.lua
  
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Lua
      uses: MunifTanjim/luver-action@v1

    - run: |
        luver install lua 5.4.3
        luver use 5.4.3
        luver install luarocks 3.8.0
        luarocks install luacheck
        luarocks install luaunit
        luarocks install luassert
        
      

    - name: Run Test script
      run: lua ./temas/inyeccion/lua/testInyeccion.lua