name: Ruby Lambdas Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - name: Run script Ruby
      run: ruby ./temas/lambdas/ruby/lambdas.rb
    
    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update test
        commit_user_name: SBaston [GitHub Actions]
        commit_user_email: sergiojose.bastonlosey@alum.uca.es